### ISSUE TITLE
Set disk to null in the default config file

### ISSUE THREAD

**Issue by vguerrerobosch** [driesvints/blade-icons#128]
### Library version

v1.0.0

### Laravel version

v.8.12

### PHP version

7.4

### Description

When installing and uncommenting the default set in the config file, you also need need to set `disk` to `null` instead of empty string, otherwise  you get the error
```
The [resources/svg] path for the "default" set does not exist.
```

### Steps to reproduce

Follow the install instructions.

**Comment by driesvints** [comment]
Thanks for reporting. I released v1.0.1 with a fix for this.

**Comment by sebastiaanluca** [comment]
On 1.0.1, this still throws an exception if the `disk` key is an empty string:

```
BladeUI\Icons\Exceptions\CannotRegisterIconSet
The [public/images] path for the "default" set does not exist. 
```

Setting it to `null` resolves the issue.

**Comment by driesvints** [comment]
@sebastiaanluca does the directory exists? Can you paste your full blade-icons.php config please?

**Comment by sebastiaanluca** [comment]
Yes, the path exists from the root of the project. Upgraded from v0.5, I think. Replaced the old config with the package's new one and updated our values.

<details>
<summary>New, non-working configuration</summary>

```php
<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Icons Sets
    |--------------------------------------------------------------------------
    |
    | With this config option you can define a couple of
    | default icon sets. Provide a key name for your icon
    | set and a combination from the options below.
    |
    */

    'sets' => [
        'default' => [

            /*
            |-----------------------------------------------------------------
            | Icons Path
            |-----------------------------------------------------------------
            |
            | Provide the relative path from your app root to your SVG icons
            | directory. Icons are loaded recursively so there's no need to
            | list every sub-directory.
            |
            | Relative to the disk root when the disk option is set.
            |
            */

            'path' => 'public/images',

            /*
            |-----------------------------------------------------------------
            | Filesystem Disk
            |-----------------------------------------------------------------
            |
            | Optionally, provide a specific filesystem disk to read
            | icons from. When defining a disk, the "path" option
            | starts relatively from the disk root.
            |
            */

            'disk' => '',

            /*
            |-----------------------------------------------------------------
            | Default Prefix
            |-----------------------------------------------------------------
            |
            | This config option allows you to define a default prefix for
            | your icons. The dash separator will be applied automatically
            | to every icon name. It's required and needs to be unique.
            |
            */

            'prefix' => 'icon',

            /*
            |-----------------------------------------------------------------
            | Fallback Icon
            |-----------------------------------------------------------------
            |
            | This config option allows you to define a fallback
            | icon when an icon in this set cannot be found.
            |
            */

            'fallback' => '',

            /*
            |-----------------------------------------------------------------
            | Default Set Classes
            |-----------------------------------------------------------------
            |
            | This config option allows you to define some classes which
            | will be applied by default to all icons within this set.
            |
            */

            'class' => '',

            /*
            |-----------------------------------------------------------------
            | Default Set Attributes
            |-----------------------------------------------------------------
            |
            | This config option allows you to define some attributes which
            | will be applied by default to all icons within this set.
            |
            */

            'attributes' => [
                // 'width' => 50,
                // 'height' => 50,
            ],

        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Global Default Classes
    |--------------------------------------------------------------------------
    |
    | This config option allows you to define some classes which
    | will be applied by default to all icons.
    |
    */

    'class' => '',

    /*
    |--------------------------------------------------------------------------
    | Global Default Attributes
    |--------------------------------------------------------------------------
    |
    | This config option allows you to define some attributes which
    | will be applied by default to all icons.
    |
    */

    'attributes' => [
        // 'width' => 50,
        // 'height' => 50,
    ],

    /*
    |--------------------------------------------------------------------------
    | Global Fallback Icon
    |--------------------------------------------------------------------------
    |
    | This config option allows you to define a global fallback
    | icon when an icon in any set cannot be found. It can
    | reference any icon from any configured set.
    |
    */

    'fallback' => '',

    /*
    |--------------------------------------------------------------------------
    | Components
    |--------------------------------------------------------------------------
    |
    | These config options allow you to define some
    | settings related to Blade Components.
    |
    */

    'components' => [
        /*
        |----------------------------------------------------------------------
        | Disable Components
        |----------------------------------------------------------------------
        |
        | This config option allows you to disable Blade components
        | completely. It's useful to avoid performance problems
        | when working with large icon libraries.
        |
        */

        'disabled' => false,

        /*
        |----------------------------------------------------------------------
        | Default Icon Component Name
        |----------------------------------------------------------------------
        |
        | This config option allows you to define the name
        | for the default Icon class component.
        |
        */

        'default' => 'icon',
    ],
];
```
</details>

**Comment by maxxscho** [comment]
Same here. I've upgraded from v.0.5.1 and with `'disk' => '',` in the config I get the same error. Setting `disk` to `null` works.

**Comment by driesvints** [comment]
I still can't reproduce this. There's go to be something very specific with your installs @sebastiaanluca @maxxscho. Can you both try on a fresh laravel install? Blade Icons clearly cannot find the directory you've set for the default installation and I'm pretty sure it's not using a filesystem disk but rather Laravel's local filesystem.

I'd like to get to the bottom of this before attempting another fix. Please make 100% sure that your icon directory exists.

**Comment by driesvints** [comment]
I also pushed a new release 1.0.2 that could maybe fix this.

**Comment by driesvints** [comment]
Gonna close this one. Please give me specific steps to reproduce the issue if you're still experiencing this.

**Comment by maxxscho** [comment]
In my case 1.0.2 fixed the issue. Thank you very much!
